test remote interruption when initializing a class requires a resource
Real world stack trace was something like that:

```
Feb 10, 2020 5:51:39 PM hudson.remoting.UserRequest perform
WARNING: LinkageError while performing UserRequest:hudson.maven.MavenModuleSetBuild$PomParser@38569db8
java.lang.ExceptionInInitializerError
	at hudson.maven.MavenModuleSetBuild$PomParser.invoke(MavenModuleSetBuild.java:1276)
	at hudson.maven.MavenModuleSetBuild$PomParser.invoke(MavenModuleSetBuild.java:1126)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3071)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: hudson.remoting.RemotingSystemException: java.lang.InterruptedException
	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:299)
	at com.sun.proxy.$Proxy5.getResource2(Unknown Source)
	at hudson.remoting.RemoteClassLoader.findResource(RemoteClassLoader.java:426)
	at java.lang.ClassLoader.getResource(ClassLoader.java:1090)
	at java.lang.Class.getResource(Class.java:2267)
	at org.jvnet.localizer.ResourceProvider$1.getResource(ResourceProvider.java:53)
	at org.jvnet.localizer.ResourceProvider.findResource(ResourceProvider.java:45)
	at org.jvnet.localizer.ResourceBundleHolder.get(ResourceBundleHolder.java:107)
	at org.jvnet.localizer.ResourceBundleHolder.get(ResourceBundleHolder.java:128)
	at org.jvnet.localizer.Localizable.toString(Localizable.java:67)
	at hudson.security.PermissionGroup.<init>(PermissionGroup.java:64)
	at hudson.model.Run.<clinit>(Run.java:2535)
	... 11 more
Caused by: java.lang.InterruptedException
	at java.lang.Object.wait(Native Method)
	at hudson.remoting.Request.call(Request.java:177)
	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:286)
	... 22 more
```

(and then "java.lang.NoClassDefFoundError: Could not initialize class hudson.maven.MavenModuleSetBuild"
when trying to use the Maven plugin again on the same agent)