restore compatability for older versions
3244.vf7f977e04755 requires the agent to be upgraded in lockstep with
Jenkins to avoid remoting errors such as:

java.lang.IllegalStateException: Unable to call getName. No matching method found in [interface hudson.remoting.RemoteClassLoader$IClassLoader] for hudson.remoting.RemoteClassLoader$ClassLoaderProxy@2cdf8d8a[jdk.internal.loader.ClassLoaders$AppClassLoader@2cdf8d8a]

This restores the compatability by specifically handling a method call
to getName for the IClassLoader and returning a dummy value if the
remote version is older than 3244