ClassFilter is not creating a new ClassLoader.
A full test cycle on Jenkins core revealed a problem, which appears to
be caused by a proxy class being defined in filtering ClassLoader.

This fix makes relevant ObjectInputStream more directly deal with
ClassFilter to eliminate this intermediate ClassLoader.

Failed tests:
  ToolLocationNodePropertyTest>HudsonTestCase.runBare:293->HudsonTestCase.runTest:433->testNativeMaven:173->HudsonTestCase.assertBuildStatus:939 unexpected build status; build log was:
------
Legacy code started this job.  No cause information is available
Building remotely on ha:AAAAnB+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAy2EgYB/eT83ILSktQi/eKcxLJUAwCuxmeFxQAAAA==slave0 (slave) in workspace /home/kohsuke/ws/jenkins/security/jenkins/test/target/hudson1757924264525954831test/workspace/test1
Deleting existing workspace /home/kohsuke/ws/jenkins/security/jenkins/test/target/hudson1757924264525954831test/workspace/test1
Staging file:/home/kohsuke/ws/jenkins/security/jenkins/test/target/classes/simple-projects.zip
Parsing POMs
Discovered a new module com.example:test.prop.hudson test.prop.hudson
Modules changed, recalculating dependency graph
ERROR: Failed to parse POMs
ha:AAAAWB+LCAAAAAAAAP9b85aBtbiIQSmjNKU4P08vOT+vOD8nVc8DzHWtSE4tKMnMz/PLL0ldFVf2c+b/lb5MDAwVRQxSaBqcITRIIQMEMIIUFgAAckCEiWAAAAA=java.io.IOException: Remote call on slave0 failed
        at hudson.remoting.Channel.call(Channel.java:789)
        at hudson.maven.AbstractMavenProcessFactory.newProcess(AbstractMavenProcessFactory.java:263)
        at hudson.maven.ProcessCache.get(ProcessCache.java:235)
        at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.doRun(MavenModuleSetBuild.java:759)
        at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:533)
        at hudson.model.Run.execute(Run.java:1745)
        at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:529)
        at hudson.model.ResourceController.execute(ResourceController.java:89)
        at hudson.model.Executor.run(Executor.java:240)
Caused by: java.lang.IllegalAccessError: class hudson.maven.$Proxy349 cannot access its superinterface hudson.maven.AbstractMavenProcessFactory$Acceptor
        at java.lang.reflect.Proxy.defineClass0(Native Method)
        at java.lang.reflect.Proxy.getProxyClass0(Proxy.java:636)
        at java.lang.reflect.Proxy.getProxyClass(Proxy.java:415)
        at hudson.remoting.MultiClassLoaderSerializer$Input.resolveProxyClass(MultiClassLoaderSerializer.java:149)
        at java.io.ObjectInputStream.readProxyDesc(ObjectInputStream.java:1549)
        at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1511)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1750)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1347)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:369)
        at hudson.remoting.UserRequest.deserialize(UserRequest.java:185)
        at hudson.remoting.UserResponse.retrieve(UserRequest.java:218)
        at hudson.remoting.Channel.call(Channel.java:781)
        ... 8 more
Finished: FAILURE

------
 expected:<SUCCESS> but was:<FAILURE>
  EnvVarsInConfigTasksTest>HudsonTestCase.runBare:293->HudsonTestCase.runTest:433->testNativeMavenOnSlave:197->HudsonTestCase.assertBuildStatusSuccess:964->HudsonTestCase.assertBuildStatus:939 unexpected build status; build log was:
------
Legacy code started this job.  No cause information is available
Building remotely on ha:AAAAnB+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAy2EgYB/eT83ILSktQi/eKcxLJUAwCuxmeFxQAAAA==slave0 (slaveEnv) in workspace /home/kohsuke/ws/jenkins/security/jenkins/test/target/hudson5317957625661338832test/workspace/test0
Deleting existing workspace /home/kohsuke/ws/jenkins/security/jenkins/test/target/hudson5317957625661338832test/workspace/test0
Staging file:/home/kohsuke/ws/jenkins/security/jenkins/test/target/classes/simple-projects.zip
Parsing POMs
Discovered a new module com.example:test.prop.hudson test.prop.hudson
Modules changed, recalculating dependency graph
ERROR: Failed to parse POMs
ha:AAAAWB+LCAAAAAAAAP9b85aBtbiIQSmjNKU4P08vOT+vOD8nVc8DzHWtSE4tKMnMz/PLL0ldFVf2c+b/lb5MDAwVRQxSaBqcITRIIQMEMIIUFgAAckCEiWAAAAA=java.io.IOException: Remote call on slave0 failed
        at hudson.remoting.Channel.call(Channel.java:789)
        at hudson.maven.AbstractMavenProcessFactory.newProcess(AbstractMavenProcessFactory.java:263)
        at hudson.maven.ProcessCache.get(ProcessCache.java:235)
        at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.doRun(MavenModuleSetBuild.java:759)
        at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:533)
        at hudson.model.Run.execute(Run.java:1745)
        at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:529)
        at hudson.model.ResourceController.execute(ResourceController.java:89)
        at hudson.model.Executor.run(Executor.java:240)
Caused by: java.lang.IllegalAccessError: class hudson.maven.$Proxy598 cannot access its superinterface hudson.maven.AbstractMavenProcessFactory$Acceptor
        at java.lang.reflect.Proxy.defineClass0(Native Method)
        at java.lang.reflect.Proxy.getProxyClass0(Proxy.java:636)
        at java.lang.reflect.Proxy.getProxyClass(Proxy.java:415)
        at hudson.remoting.MultiClassLoaderSerializer$Input.resolveProxyClass(MultiClassLoaderSerializer.java:149)
        at java.io.ObjectInputStream.readProxyDesc(ObjectInputStream.java:1549)
        at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1511)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1750)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1347)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:369)
        at hudson.remoting.UserRequest.deserialize(UserRequest.java:185)
        at hudson.remoting.UserResponse.retrieve(UserRequest.java:218)
        at hudson.remoting.Channel.call(Channel.java:781)
        ... 8 more
Finished: FAILURE

------
 expected:<SUCCESS> but was:<FAILURE>

Tests run: 1232, Failures: 2, Errors: 0, Skipped: 3